name: 'Get and cache dependencies'
description: 'Get and cache dependencies'
runs:
  using: 'composite'
  steps:
    # en este step nop hace falta agregar shell:bash
    - name: Cache dependencies
      id: cache_dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install_dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci 
      shell: bash # esto de bebe agregar para saber que es un shell bash         